### PR TITLE
fix: Fix useFunnel return values and parameter type

### LINKED ISSUE #1: [fix] useFunnel fix of return values and parameter type
### 1. I'm unable to pass an array, but I'd like to be able to do. 
image

image

### 2. During UI work, there might be a need for the `currentStep`

### PR DESCRIPTION
**Pull request by altmit**
## Overview
closes #1 

## Changes
1. The currentStep has been added to the return values of useFunnel
2. Changed the return type of useFunnel from an array to an object
3. The parameter type of useFunnel has been changed to String[]
4. In the test code of useFunnel, parameters are now passed as an array

### CODE REVIEW

**Review by bakhacode — APPROVED** [review]

File: packages/hooks/useFunnel/useFunnel.tsx [hunk 1]
```diff
@@ -41,5 +41,5 @@ export default function useFunnel<S extends string>(steps: [S, ...S[]]) {
     [currentStep]
   );
 
-  return [FunnelComponent, changeStep] as const;
+  return { currentStep, FunnelComponent, changeStep } as const;
```
Comment (Kakamotobi) [inline packages/hooks/useFunnel/useFunnel.tsx:44]: While you're at it, I think adjusting the names like below is more clear and will provide better experience on the user end.

`Funnel --> FunnelComponent`
`FunnelComponent --> FunnelComponentMemo`
`{ FunnelComponent }` --> `{ Funnel: FunnelComponentMemo }`

Comment (altmit) [reply packages/hooks/useFunnel/useFunnel.tsx]: Modification completed👍
[98a1998](https://github.com/fine-ants/demolition/pull/2/commits/98a1998f290bf747a2c1699ffbb631a8a4e2877b)
